name: Check For ZAP Errors
on:
  workflow_dispatch:
  schedule:
    # Every day at 2am
    - cron:  '0 2 * * *'

jobs:
  CheckForErrors:
    runs-on: ubuntu-latest
    steps:
      - name: "Check For Errors"
        run: docker run --rm -v $(pwd)/.github/workflows/conf:/zap/wrk/:rw -t zaproxy/zap-stable:latest zap.sh -addonupdate -cmd -autorun /zap/wrk/check-zap-errors.yaml
